package ClientSide;

import java.net.*;
import java.io.*;

/*
 * Client Application GUI.
 * Steps:
 *   1. Fill in My Name, My Port, Finder Host, Finder Port then click Register.
 *   2. Type a target client name and click Find.
 *   3. After a successful Find, click Connect to connect directly to that client.
 *   4. Click Unregister when done.
 *
 * To run three clients on one machine use different My Port values, e.g. 6001, 6002, 6003.
 */
public class ClientForm extends javax.swing.JFrame {

    static ClientForm instance;
    String myCode = null;
    String foundHost = null;
    int foundPort = 0;
    String foundCode = null;

    /**
     * Creates new form ClientForm
     */
    public ClientForm() {
        initComponents();
        instance = this;
        jTextArea1.setEditable(false);
        jButton2.setEnabled(false);
        jButton4.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Client Application");

        jLabel2.setText("My Name:");

        jTextField1.setText("Client1");

        jLabel3.setText("My Port:");

        jTextField2.setText("6000");

        jLabel4.setText("Finder Host:");

        jTextField3.setText("localhost");

        jLabel5.setText("Finder Port:");

        jTextField4.setText("5000");

        jButton1.setText("Register");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Unregister");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel6.setText("Find Name:");

        jButton3.setText("Find");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Connect");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addGap(8, 8, 8)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Register with Finder Server
        String name = jTextField1.getText().trim();
        int peerPort, finderPort;
        try {
            peerPort = Integer.parseInt(jTextField2.getText().trim());
            finderPort = Integer.parseInt(jTextField4.getText().trim());
        } catch (Exception e) {
            log("Error: Port must be a number.");
            return;
        }
        String finderHost = jTextField3.getText().trim();
        String host = "localhost";
        try { host = InetAddress.getLocalHost().getHostAddress(); } catch (Exception e) { log("Using localhost for host."); }
        try {
            Socket s1 = new Socket(finderHost, finderPort);
            DataOutputStream out = new DataOutputStream(s1.getOutputStream());
            DataInputStream input = new DataInputStream(s1.getInputStream());
            out.writeUTF("REGISTER " + name + " " + host + " " + peerPort);
            String response = input.readUTF();
            input.close();
            out.close();
            s1.close();
            if (response.startsWith("OK")) {
                myCode = response.split(" ")[1];
                log("Registered successfully. My code: " + myCode);
                jButton1.setEnabled(false);
                jButton2.setEnabled(true);
                jTextField1.setEditable(false);
                jTextField2.setEditable(false);
                // start peer server to accept incoming connections
                Thread t = new Thread(new PeerServer(peerPort, myCode));
                t.start();
            } else {
                log("Registration failed: " + response);
            }
        } catch (Exception e) {
            log("Error: " + e.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // Unregister from Finder Server
        String name = jTextField1.getText().trim();
        String finderHost = jTextField3.getText().trim();
        int finderPort;
        try {
            finderPort = Integer.parseInt(jTextField4.getText().trim());
        } catch (Exception e) {
            log("Error: Port must be a number.");
            return;
        }
        try {
            Socket s1 = new Socket(finderHost, finderPort);
            DataOutputStream out = new DataOutputStream(s1.getOutputStream());
            DataInputStream input = new DataInputStream(s1.getInputStream());
            out.writeUTF("UNREGISTER " + name + " " + myCode);
            String response = input.readUTF();
            input.close();
            out.close();
            s1.close();
            if (response.equals("OK")) {
                log("Unregistered successfully.");
                myCode = null;
                jButton1.setEnabled(true);
                jButton2.setEnabled(false);
                jTextField1.setEditable(true);
                jTextField2.setEditable(true);
            } else {
                log("Unregister failed: " + response);
            }
        } catch (Exception e) {
            log("Error: " + e.getMessage());
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // Find a client by name via Finder Server
        String targetName = jTextField5.getText().trim();
        String finderHost = jTextField3.getText().trim();
        int finderPort;
        try {
            finderPort = Integer.parseInt(jTextField4.getText().trim());
        } catch (Exception e) {
            log("Error: Port must be a number.");
            return;
        }
        try {
            Socket s1 = new Socket(finderHost, finderPort);
            DataOutputStream out = new DataOutputStream(s1.getOutputStream());
            DataInputStream input = new DataInputStream(s1.getInputStream());
            out.writeUTF("FIND " + targetName);
            String response = input.readUTF();
            input.close();
            out.close();
            s1.close();
            if (response.startsWith("FOUND")) {
                String[] parts = response.split(" ");
                foundHost = parts[1];
                foundPort = Integer.parseInt(parts[2]);
                foundCode = parts[3];
                log("Found " + targetName + " at " + foundHost + ":" + foundPort + "  code=" + foundCode);
                jButton4.setEnabled(true);
            } else {
                log(targetName + " is not registered.");
                jButton4.setEnabled(false);
            }
        } catch (Exception e) {
            log("Error: " + e.getMessage());
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // Connect directly to the found client
        String myName = jTextField1.getText().trim();
        try {
            Socket s1 = new Socket(foundHost, foundPort);
            DataOutputStream out = new DataOutputStream(s1.getOutputStream());
            DataInputStream input = new DataInputStream(s1.getInputStream());
            out.writeUTF("CONNECT " + myName + " " + foundCode);
            String response = input.readUTF();
            input.close();
            out.close();
            s1.close();
            log("Connect response: " + response);
        } catch (Exception e) {
            log("Error: " + e.getMessage());
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    public static void log(String msg) {
        if (instance != null) {
            instance.jTextArea1.append(msg + "\n");
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClientForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
