package finderserver;

import java.io.*;
import java.net.*;
import java.util.*;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

/**
 * Finder Server GUI - manages client registrations and lookup requests.
 */
public class FinderServerGUI extends javax.swing.JFrame {

    private Map<String, ClientRecord> clients = new HashMap<>();
    private ServerSocket serverSocket;
    private volatile boolean running = false;
    private DefaultTableModel tableModel;

    /**
     * Creates new form FinderServerGUI
     */
    public FinderServerGUI() {
        initComponents();
        tableModel = (DefaultTableModel) jTable1.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Finder Server");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Finder Server");

        jLabel2.setText("Server Port:");

        jTextField1.setText("5000");

        jButton1.setText("Start Server");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Stop Server");
        jButton2.setEnabled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel3.setText("Registered Clients:");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {},
            new String [] {"Name", "Host", "Port", "Unique Code"}
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel4.setText("Server Log:");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setEditable(false);
        jScrollPane2.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 560, Short.MAX_VALUE)
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane2))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(15, 15, 15)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        startServer();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        stopServer();
    }//GEN-LAST:event_jButton2ActionPerformed

    // -------------------------------------------------------------------------
    // Server logic
    // -------------------------------------------------------------------------

    private void startServer() {
        try {
            int port = Integer.parseInt(jTextField1.getText().trim());
            if (port < 1 || port > 65535) {
                log("Error: Port must be between 1 and 65535.");
                return;
            }
            serverSocket = new ServerSocket(port);
            running = true;
            jButton1.setEnabled(false);
            jButton2.setEnabled(true);
            jTextField1.setEditable(false);
            log("Server started on port " + port);
            new Thread(new Runnable() {
                public void run() {
                    while (running) {
                        try {
                            Socket s = serverSocket.accept();
                            log("New connection from: " + s.getInetAddress().getHostAddress());
                            new Thread(new ClientHandler(s, FinderServerGUI.this)).start();
                        } catch (Exception e) {
                            if (running) {
                                log("Accept error: " + e.getMessage());
                            }
                        }
                    }
                }
            }).start();
        } catch (Exception e) {
            log("Error starting server: " + e.getMessage());
        }
    }

    private void stopServer() {
        running = false;
        try {
            if (serverSocket != null) {
                serverSocket.close();
            }
        } catch (Exception e) {
        }
        jButton1.setEnabled(true);
        jButton2.setEnabled(false);
        jTextField1.setEditable(true);
        log("Server stopped.");
    }

    /**
     * Registers a new client. Returns the unique code, or null if name taken.
     */
    public synchronized String registerClient(String name, String host, int port) {
        if (clients.containsKey(name)) {
            return null;
        }
        String code = java.util.UUID.randomUUID().toString().substring(0, 8).toUpperCase();
        ClientRecord record = new ClientRecord(name, host, port, code);
        clients.put(name, record);
        final String fName = name, fHost = host, fCode = code;
        final int fPort = port;
        SwingUtilities.invokeLater(new Runnable() {
            public void run() {
                tableModel.addRow(new Object[]{fName, fHost, fPort, fCode});
            }
        });
        log("Registered: " + name + " at " + host + ":" + port + "  code=" + code);
        return code;
    }

    /**
     * Looks up a client by name. Returns null if not found.
     */
    public synchronized ClientRecord findClient(String name) {
        ClientRecord record = clients.get(name);
        if (record != null) {
            log("Lookup: " + name + " -> found");
        } else {
            log("Lookup: " + name + " -> not registered");
        }
        return record;
    }

    /**
     * Unregisters a client. Returns true on success.
     */
    public synchronized boolean unregisterClient(String name, String code) {
        ClientRecord record = clients.get(name);
        if (record == null || !record.getUniqueCode().equals(code)) {
            return false;
        }
        clients.remove(name);
        SwingUtilities.invokeLater(new Runnable() {
            public void run() {
                for (int i = 0; i < tableModel.getRowCount(); i++) {
                    if (tableModel.getValueAt(i, 0).equals(name)) {
                        tableModel.removeRow(i);
                        break;
                    }
                }
            }
        });
        log("Unregistered: " + name);
        return true;
    }

    /**
     * Appends a message to the server log (thread-safe).
     */
    public void log(String message) {
        SwingUtilities.invokeLater(new Runnable() {
            public void run() {
                jTextArea1.append(message + "\n");
                jTextArea1.setCaretPosition(jTextArea1.getDocument().getLength());
            }
        });
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FinderServerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FinderServerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FinderServerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FinderServerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FinderServerGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
